variable "aws-region" {}
variable "env" {}
variable "cluster-name" {}
variable "vpc-cidr" {}
variable "vpc-name" {}
variable "igw-name" {}
variable "pub-subnet-count" {}
variable "pub-cidr-block" {}
variable "pub-availability-zone" {}
variable "pub-sub-name" {}
variable "pri-subnet-count" {}
variable "pri-availability-zone" {}
variable "pri-sub-name" {}
variable "public-rt-name" {}
variable "pri-cidr-block" {}
